language: scala
scala:
  - 2.11.8

branches:
  only:
    - develop
    - master

sudo: required
services:
  - docker

before_deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - git checkout $TRAVIS_BRANCH

deploy:
  provider: script
  skip_cleanup: true
  script: sbt ++$TRAVIS_SCALA_VERSION dockerBuildAndPush
  on:
    all_branches: true
