language: scala
scala:
  - 2.11.8

branches:
  only:
    - develop
    - master

sudo: required
services:
  - docker

before_deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - git checkout $TRAVIS_BRANCH
  - if [ "$TRAVIS_BRANCH" == "master" ]; then git tag v$(sbt --error "export version" 2>/dev/null); fi

deploy:
  provider: script
  skip_cleanup: true
  script: sbt ++$TRAVIS_SCALA_VERSION dockerBuildAndPush
  on:
    all_branches: true
